#pragma once

#include <glm/glm.hpp>

#ifndef L2DE_DEBUG
	#define L2DE_DEBUG (_DEBUG || 0)
#endif

#if L2DE_DEBUG && !defined(L2DE_DEBUG_MAX_BASE_DELTATIME)
	#define L2DE_DEBUG_MAX_BASE_DELTATIME 0.1f
#endif

//Colliders
#if L2DE_DEBUG && !defined(L2DE_DEBUG_SHOW_COLLIDER)
	#define L2DE_DEBUG_SHOW_COLLIDER 1
#endif

#ifndef L2DE_DEBUG_SHOW_COLLIDER_DEFAULT_VALUE
	#define L2DE_DEBUG_SHOW_COLLIDER_DEFAULT_VALUE 1
#endif

#ifndef L2DE_DEBUG_SHOW_COLLIDER_DEFAULT_LAYER
	#define L2DE_DEBUG_SHOW_COLLIDER_DEFAULT_LAYER 10000
#endif

#ifndef L2DE_DEBUG_SHOW_COLLIDER_COLOR
	#define L2DE_DEBUG_SHOW_COLLIDER_COLOR glm::vec4(0.6f, 1.0f, 0.5f, 0.9f)
#endif

#ifndef L2DE_DEBUG_SHOW_COLLIDER_TRIGGER_COLOR
	#define L2DE_DEBUG_SHOW_COLLIDER_TRIGGER_COLOR glm::vec4(1.0f, 0.8f, 0.5f, 0.9f)
#endif

//Position
#ifndef L2DE_DEBUG_SHOW_POSITION_DEFAULT_VALUE
	#define L2DE_DEBUG_SHOW_POSITION_DEFAULT_VALUE 0
#endif

#ifndef L2DE_DEBUG_SHOW_POSITION_DEFAULT_TEXT_LAYER
	#define L2DE_DEBUG_SHOW_POSITION_DEFAULT_TEXT_LAYER 11000
#endif

#ifndef L2DE_DEBUG_SHOW_POSITION_DEFAULT_BOX_LAYER
	#define L2DE_DEBUG_SHOW_POSITION_DEFAULT_BOX_LAYER 10999
#endif

#ifndef L2DE_DEBUG_SHOW_POSITION_TEXT_COLOR
	#define L2DE_DEBUG_SHOW_POSITION_TEXT_COLOR glm::vec4(1.0f, 1.0f, 1.0f, 1.0f)
#endif

#ifndef L2DE_DEBUG_SHOW_POSITION_BOX_COLOR
	#define L2DE_DEBUG_SHOW_POSITION_BOX_COLOR glm::vec4(0.0f, 0.0f, 0.0f, 0.7f)
#endif

#ifndef L2DE_DEBUG_SHOW_POSITION_BOX_PADDING
	#define L2DE_DEBUG_SHOW_POSITION_BOX_PADDING 5.0f
#endif